### ISSUE TITLE
Tracks are the new streams

### ISSUE THREAD

**Issue by jensengar** [otalk/jingle-media-session#33]
The recent change to the webrtc proposal seems to be chopping us out at the knees. Everything will be track related rather than stream related (https://www.w3.org/standards/history/webrtc). Is there a migration plan for this?

**Comment by fippo** [comment]
i do not think the wg has a migration plan (nor cares) :-/

see https://blog.mozilla.org/webrtc/the-evolution-of-webrtc/

**Comment by jensengar** [comment]
So if FF removes the deprecated stream functions, we will just rely on shims and continue to use streams?

**Comment by fippo** [comment]
I doubt that is going to happen before 2020 (or 2025). Might be worth running https://github.com/fippo/webrtc-codemods over this repo but i've found the process of migrating to the "1.0" API to be a lot more complicated (and time-consuming)
