### ISSUE TITLE
Throw an error when trying to remove (or switch/replace) an unknown stream

### ISSUE THREAD

**Issue by xdumaine** [otalk/jingle-media-session#6]
If calling removeStream or switchStream with a stream to be removed, and that stream is not a local stream on the peerconnection, `pc.removeStream(stream)` will basically just silently do nothing - we should maybe check that the stream exists in `pc.getLocalStreams()` before trying to remove it, and error otherwise.

**Comment by fippo** [comment]
but the long-term plan (once chrome supports audio and video) is to allow remotestreams... but then, the forwarded stream will be in .localStreams so... tentative +1?
