### ISSUE TITLE
Support Firefox Multistream

### ISSUE THREAD

**Issue by xdumaine** [otalk/jingle-media-session#7]
I think this was discussed previously, but I thought it would be good to have an issue open - now that firefox supports multistream, supporting it should be a (not so simple) matter of SDP interop described in [Firefox multistream hacks](https://hacks.mozilla.org/2015/06/firefox-multistream-and-renegotiation-for-jitsi-videobridge/).

**Comment by xdumaine** [comment]
Link to SDP interop - https://github.com/jitsi/sdp-interop/blob/d4569a12875a7180004726633793430eccd7f47b/lib/interop.js

**Comment by fippo** [comment]
the approach of sdp-interop to transform SDP is fundamentally wrong. Doing it right is on my TODO list.

**Comment by xdumaine** [comment]
Fair enough. Feel free to close this then. If I can help with that, I'll do my best to.

**Comment by fippo** [comment]
changed the title instead :-)

The biggest issue here is that for jingle and our use-case we actually want POF/PAN as described in https://tools.ietf.org/html/draft-roach-mmusic-pof-pan-02
This maps very closely to the source-add/source-remove things, possibly even content-add/content-remove.
